### ISSUE TITLE
Curl command

### ISSUE THREAD

**Issue by BoFFire** [PastaGringo/Mastodon.sh#3]
Hi,
Curl line 89 sould be installed before executing in line 89 ;) or think about alternative using wget.
Regards,

**Comment by PastaGringo** [comment]
That's ok now ! 

https://github.com/PastaGringo/Mastodon.sh/commit/e953aa425cf3f99b32b6b7dd0be68488baa2ac69

Thanks

**Comment by PastaGringo** [comment]
That's ok now ! https://github.com/PastaGringo/Mastodon.sh/commit/e953aa425cf3f99b32b6b7dd0be68488baa2ac69

Thanks
